PREFIX ghg: <https://simon5530.github.io/ghg-assurance-graph/ns/0.1/>
PREFIX prov: <http://www.w3.org/ns/prov#>
SELECT DISTINCT ?result ?version WHERE {
 ?target (prov:wasRevisionOf|^prov:wasRevisionOf)* ?result.
 ?result a ghg:EmissionResult; ghg:version ?version.
}
